server:
  port: 8080
  servlet:
    context-path: /wx-api

spring:
  application:
    name: wx-shop
  # redis配置
  data:
    redis:
      database: 1
      host: 43.139.67.232
      port: 6379
      password: '!Yang1345433'
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.67.232:3306/wx_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: '!Yang1345433'

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

# 健康检查
management:
  endpoint:
    health:
      probes:
        enabled: true

# 日志
logging:
  level:
    yangcdtu.cn.wxshop.mapper: debug
    yangcdtu.cn.wxshop.common.advance: debug

# minio存储设置
minio:
  auth:
    # noinspection SpringBootApplicationYaml
    url: 'http://43.139.67.232:9000'
    # noinspection SpringBootApplicationYaml
    access-key: 'admin'
    # noinspection SpringBootApplicationYaml
    secret-key: 'admin123'

# swagger 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '用户'
      paths-to-match: '/user/**'
    - group: '测试'
      paths-to-match: '/test/**'
    - group: '认证'
      paths-to-match:
        - '/auth/**'